### ISSUE TITLE
CSRF_detected

### ISSUE THREAD

**Issue by haobo-chen** [NeverMin/omniauth-wechat-oauth2#12] opened 2015-07-24 21:44 UTC
Here is my code:

``` ruby
# routes.rb
get '/auth/wechat/callback', :to => 'sessions#create'
get '/auth/failure', :to => 'sessions#failure'

#sessions_controller
def create
    auth_hash = request.env['omniauth.auth']
    render :text => auth_hash.inspect
end

def failure
    flash[:notice] = params[:message]
end
```

I receive the callback failure with "csrf_detected" message. 
If I add `:provider_ignores_state => true`, I only get this incomplete hash:

```
# extra=#> info=# provider="wechat" uid="oGpnCvkYbkHwXpGYjvKXU9Zjbvx8">
```

**Comment by NeverMin** [comment] 2019-03-18 06:10
Duplicate of #1

**Closed by NeverMin** 2019-03-18 06:10 UTC
Labels: duplicate
